config/routes.rb
Rails.application.routes.draw do
  
  
  root 'posts#index'

  get '', to:'posts#index'
  get  '/newpost',  to: 'posts#new'
  post   '/newpost',   to: 'posts#create'
  get  '/select',  to: 'posts#select'
  get  '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get  '/comment/new',  to: 'comments#new'
  post   '/comment/create',   to: 'comments#create'
  resources :users do
    resources :comments
  end
  resources :posts do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates :user_id, presence: true
  validates :post_id, presence: true
  validates :comment_content, presence: true, length: { maximum: 500 }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  # default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 100 }
  validates :content, presence: true, length: { maximum: 100000 }
  def increment(by = 1)
    self.view ||= 0
    self.view += by
    self.save
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    validates :city, presence: true, length: { maximum: 50 }
    VALID_MOBILE_REGEX = /[0-9]{10,13}/
    validates :mobile,  presence: true, format: { with: VALID_MOBILE_REGEX }
                      # format: { with: VALID_MOBILE_REGEX } 
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: true
    has_secure_password
    validates :password, presence: true, length: { minimum: 8,maximum:20 }

      # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper

    private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        #store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :logged_in_user, only: [:new, :create, :destroy]

  def index
    @comment = Comment.all
    @users = User.all
    @comments = Comment.where("created_at >= ?", 1.month.ago.utc).order(created_at: :desc)
    @recentcomment= Comment.order(updated_at: :desc).limit(10)
  end

  def show
    @comment = Comment.find(params[:id])
    @posts = Post.all.includes(:comments)
    @users = User.all
    @recentcomment= Comment.order(updated_at: :desc).limit(10)
    
  end

  def new
    @comment = Comment.new()
  end

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id
    if @comment.save
      flash[:success] = "New comment created!"
      redirect_to post_path(@post)
    else
      render 'posts/show'
    end
  end

  def destroy 
  end

  private

  def comment_params
    params.require(:comment).permit(:comment_content)
  end
  
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  layout "rad"

  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :logged_in_user, only: [ :new, :create, :destroy]
    
    def show
      @post = Post.find(params[:id])
      @post.increment
      @users = User.all
      @toppost = Post.order(view: :desc).limit(5)
      @recentpost= Post.order(updated_at: :desc).limit(12)
      @comment = @post.comments
    end

    def index
        @posts = Post.where("created_at >= ?", 1.month.ago.utc).order(created_at: :desc)
        @users = User.all
        @toppost = Post.order(view: :desc).limit(5)
        @recentpost= Post.order(updated_at: :desc).limit(12)

        respond_to do |format|
          format.html # select.html.erb
          format.js # select.js.erb
          format.json { render json: @posts }
        end
    end

    def select
      @posts = Post.where("created_at >= ?", 1.month.ago.utc).order(created_at: :desc)
      @users = User.all
      @toppost = Post.order(view: :desc).limit(5)
      @recentpost= Post.order(updated_at: :desc).limit(12)
    end


    def new
      @post = Post.new()
    end

    def create
        @post = current_user.posts.build(post_params)
        if @post.save
          # flash[:success] = "New post created!"
          redirect_to root_url
        else
          render 'new'
        end
    end

    def destroy 
    end


  
    private

    def post_params
      params.permit(:title, :content, :topic)
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
      log_in user
      #redirect_to user 
      redirect_to root_path

      
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to login_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def show
    @user = User.find(params[:id])
    @posts = @user.posts
    @comments = @user.comments
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the News+ App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name,:city, :mobile, :email, :password,
                                   :password_confirmation)
    end

        # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
  def full_title(page_title = '')
    base_title = "News+"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    # Logs in the given user.
   def log_in(user)
        session[:user_id] = user.id
    end

      # Returns the current logged-in user (if any).
  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

    # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end

    # Logs out the current user.
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 40 })
    size         = options[:size]
    gravatar_id  = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.email, class: "gravatar")
  end
end

app/views/comments/_comment.html.erb
    
<ol class="posts">
<li>
      <span class="title"><%= link_to comment.comment_content %></span>
      &nbsp&nbsp&nbsp&nbsp &nbsp&nbsp&nbsp&nbsp
      <div class="info timestamp"><%= comment.created_at %></div>
      <div class="info topic"><%= comment.post.topic %></div>
      </li>
</ol>

app/views/comments/_form.html.erb

<div class="new-post">
<%= form_with(model: [@post, @post.comments.build ], local: true) do |f| %>
    <%= render 'shared/comment_error_msg' %>

    <div class="post-form-row">
        <div class="new-content"><%= f.text_area :comment_content, class: 'form-control', rows: "5" %></div>
    </div>

    <div class="post-button-group">
        <div class="post-buttons">
            <%= f.submit "Post", class: "btn btn-primary" %>
        </div>
    </div>
<% end %>

</div>

app/views/comments/_show.html.erb
<hr>
<p><%= @post.comments.count() %> Comments</p>
<% @post.comments.each do |comment| %>
    
    <%= comment.comment_content %>
    
    <br>
    <% end %>

app/views/hello/index.html.erb

<h1>Hello#index</h1>
<p>Find me in app/views/hello/index.html.erb</p>


app/views/layouts/_footer.html.erb
<footer class="footer text-center footer-bottom navbar-inverse">

<div>Copyright &copy; 2020  |  Powered by  Sifeng Wang - s3688201  &  Jiecai Ma - s3653360  |  Tutor: Alex </div>

</footer>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
      <%= render 'layouts/header' %>
      <div class="container">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
        <%= debug(params) if Rails.env.development? %>
      </div>
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/hello.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p>Render by layout/hello.html.erb </p>
    <%= yield %>
  </body>
</html>

app/views/layouts/rad.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p>RAD layout </p>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<ol class="posts">
    <li>
    <%= link_to gravatar_for(post.user, size: 40), post.user %>
    <div class="info user"><%= link_to post.user.name, post.user %></div>
    <span class="title"><%= link_to post.title, post %></span>
    <div class="info timestamp"><%= post.created_at %></div>
    <div class="info topic"><%= post.topic %></div>
    &nbsp&nbsp&nbsp&nbsp &nbsp&nbsp&nbsp&nbsp
    <span class="glyphicon glyphicon-comment info topic"></span>
    <div class="info"><%= post.comments.count() %></div>
    <span class="glyphicon glyphicon-eye-open info topic"></span>
    <div class="info"><%= post.view %></div>
    </li>
</ol>

app/views/posts/index.html.erb
<% provide(:title, 'Home') %>

<div class="mainbody">



  <div class="col-xs-9 col-md-7">

    <nav class="navbar navbar-light bg-light">
      <div class="list-group col-sm-8">
      <div class="list-group-a post-buttons">
        <%= link_to "Recent Post", root_path, class: "list-group-item" %>
        <%= link_to "Selected Post", select_path, class: "list-group-item" %>
        <%= link_to "My Settings", '#',class: "list-group-item" %>
      </div>
        <form class="form-inline my-2 my-lg-0 post-buttons">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" name="search">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
          </div>
        </form>
      <div class="post-buttons">
        <%= link_to "New Post", '/newpost' ,class: "btn btn-success" %>
        </div>
      </div>

      


      
    </nav>

    <section class="postslist">
    <%= render @posts %>
    </section>
  </div>

  <div class="col-xs-3 col-md-5">
    <section class="members">
      <%= render 'shared/member' %>
    </section>

    <section class="topic">
      <%= render 'shared/topic' %>
    </section>

    <section class="Post">
      <%= render 'shared/mostviewspost' %>
    </section>

    <section class="Links">
    <%= render 'shared/links' %>
    </section>
  </div>
  
</div>

app/views/posts/select.html.erb
<% provide(:title, 'Home') %>

<div class="mainbody">



  <div class="col-xs-9 col-md-7">

    <nav class="navbar navbar-light bg-light">
      <div class="list-group col-sm-8">
      <div class="list-group-a post-buttons">
        <%= link_to "Recent Post", root_path, class: "list-group-item" %>
        <%= link_to "Selected Post", select_path, class: "list-group-item" %>
        <%= link_to "My Settings", '#',class: "list-group-item" %>
      </div>
        <form class="form-inline my-2 my-lg-0 post-buttons">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search" name="search">
            <div class="input-group-btn">
              <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i></button>
            </div>
          </div>
        </form>
      <div class="post-buttons">
        <%= link_to "New Post", '/newpost' ,class: "btn btn-success" %>
        </div>
      </div>

      


      
    </nav>

    <section class="postslist">
    <%= render @posts %>
    </section>
  </div>

  <div class="col-xs-3 col-md-5">
    <section class="members">
      <%= render 'shared/member' %>
    </section>

    <section class="topic">
      <%= render 'shared/topic' %>
    </section>

    <section class="Post">
      <%= render 'shared/mostviewspost' %>
    </section>

    <section class="Links">
    <%= render 'shared/links' %>
    </section>
  </div>
  
</div>

app/views/posts/select.js.erb
$(".post").change(function(){
  var value = $(this).val()
  $.ajax({
    url: <%= stores_path(:json) %>,
    type: 'GET',
    data: value,
    success: function(data){
      $("#products_list").html(data.products)
    }
  })
})

app/views/posts/show.html.erb
<% provide(:title, 'Post') %>

<div class="col-md-8">
    <div class="mainbody">
        <div class="post-container">
            <div class="post-inner-container">
                <div class="post-area">
                    <div class="post-title"><h4><%= @post.title %></h4></div>
                    <div class="post-info">
                        <div class="col-md-7">
                            <span class="label label-default info"><%= @post.topic %></span>
                        </div>
                        <div class="col-md-3">
                            <span class="glyphicon glyphicon-comment info topic"></span>
                            &nbsp
                            <div class="info"><%= @post.comments.count() %></div>
                            &nbsp&nbsp
                            <span class="glyphicon glyphicon-eye-open info topic"></span>
                            &nbsp
                            <div class="info"><%= @post.view %></div>
                        </div>
                    </div>
                    <div class="post-user-info">
                        <div class="inner-user-info">
                            <%= gravatar_for(@post.user, size: 40) %>&nbsp&nbsp
                            <%= @post.user.name %>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
                            <div class="timestamp"><%= @post.created_at %></div>
                        </div>
                    </div>
                    <div class="post-content">
                        <p><%= @post.content %></p>
                        
                    </div>
                    <hr>
                </div>
                
                
                <div class="post-comment-area">
                
                    <p>Comment</p>
                    <div class="post-comment-form">
                    <%= render 'comments/form' %>
                    </div>
                    
                    <div class="post-comment-view">
                    <%= render 'comments/show' %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="col-md-4">
  <section class="members">
    <%= render 'shared/member' %>
  </section>

  <section class="topic">
    <%= render 'shared/topic' %>
  </section>

  <section class="Post">
    <%= render 'shared/mostviewspost' %>
  </section>

  <section class="Links">
  <%= render 'shared/links' %>
  </section>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_mostviewspost.html.erb
<div class="right-side-bar">
  <div class="spacer"></div>
    <h5 class="card-header">Post</h5>
    <div class="toppost-container">
    <% @toppost.each do |toppost| %>
            <div class="col-sm-8 toppost-left">
                <%= link_to toppost.title, toppost %>
                </div>
            <div class="col-md-2">
                <span class="glyphicon glyphicon-eye-open"></span>
                <%= toppost.view %>
            </div>


    <% end %>
    </div>
</div>

app/views/shared/_post_error_msg.html.erb
<% if @post.errors.any? %>
<div id="error_explanation">
  <div class="alert alert-danger">
    The form contains <%= pluralize(@post.errors.count, "error") %>.
  </div>
  <ul>
  <% @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_topic.html.erb
<div class="right-side-bar">
  <div class="spacer"></div>
  <h5 class="card-header">Topic</h5>
  <div class="grid-container">
      <div class="grid-item">
        <label><a>A.I.</a><%= check_box_tag("post_topic[]", "A.I.") %></label>
      </div>
      <div class="grid-item">
        <label><a>Rails</a><%= check_box_tag("post_topic[]", "Rails") %></label>
      </div>
      <div class="grid-item">
        <label><a>Go</a><%= check_box_tag("post_topic[]", "Go") %></label>
      </div>
      <div class="grid-item">
        <label><a>Game</a><%= check_box_tag("post_topic[]", "Game") %></label>
      </div>
      <div class="grid-item">
        <label><a>V.R.</a><%= check_box_tag("post_topic[]", "V.R.") %></label>
      </div>
      <div class="grid-item">
        <label><a>Vue</a><%= check_box_tag("post_topic[]", "Vue") %></label>
      </div>
      <div class="grid-item">
        <label><a>AWS</a><%= check_box_tag("post_topic[]", "AWS") %></label>
      </div>
      <div class="grid-item">
        <label><a>Web</a><%= check_box_tag("post_topic[]", "Web") %></label>
      </div>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>

      <div class="form-row">
        <div class="col-label"><%= f.label :name %></div>
        <div class="col-field">
          <%= f.text_field :name, class: 'form-control', placeholder: 'Enter your name' %>
        </div>
      </div>

      <div class="form-row">
        <div class="col-label"><%= f.label :city %></div>
        <div class="col-field">
          <%= f.text_field :city, class: 'form-control', placeholder: 'Enter your city' %>
        </div>
      </div>


      <div class="form-row">
        <div class="col-label"><%= f.label :email %></div>
        <div class="col-field">
          <%= f.email_field :email, class: 'form-control', placeholder: 'Enter your email' %>
        </div>
      </div>

      <div class="form-row">
        <div class="col-label"><%= f.label :password %></div>
        <div class="col-field">
          <%= f.password_field :password, class: 'form-control', placeholder: '8-20 characters' %>
        </div>
      </div>

      <div class="form-row">
        <div class="col-label"><%= f.label :password_confirmation, "Password Confirmation" %></div>
        <div class="col-field">
          <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'confirm password' %>
        </div>
      </div>

      <div class="form-row">
      <div class="col-label"><%= f.label :mobile %></div>
      <div class="col-field">
        <%= f.text_field :mobile, class: 'form-control', placeholder: 'Enter your mobile' %>
      </div>
      </div>

      <div class="col-label"></div>
      <div class="col-field"><%= f.submit "sign up", class: "btn btn-success" %></div>
    <% end %>
    <br>
    <div class="form-row">
    <div class="col-label"></div>
    <div class="col-field">
      <p class="form-a-link"><%= link_to "already a user?",  login_path %></p>
    </div>
  </div>
</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.email) %>
<div class="row">

    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <p class="center">
      <span class="glyphicon glyphicon-time"></span>
      Join time:<%= @user.created_at %>
      <span class="glyphicon glyphicon-map-marker"></span>
      City:<%= @user.city%>
      </p>
    </section>


  <div class="col-md-8">
  <h3 class="center">Posts (<%= @user.posts.count %>)</h3>
  <% if @user.posts.any? %>
    <ol class="posts">
      <%= render @posts %>
    </ol>
  <% end %>
  </div>
  
  <div class="col-md-8">
    <h3 class="center">Comments (<%= @user.comments.count %>)</h3>
    <% if @user.comments.any? %>
    <ol class="posts">
      <%= render @comments %>
    </ol>
  <% end %>
  </div>



</div>